[tool.poetry]
name = "quant"
version = "0.1.0"
description = ""
authors = ["Steven Guo <gcl272633743@163.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
finrl = {git = "https://github.com/AI4Finance-Foundation/FinRL.git"}
yfinance = "^0.2.55"
stockstats = "^0.5"
gym = "^0.26.2"
pandas = "^2.2.3"
numpy = "^1.24.0"  # Downgraded to be compatible with stable-baselines3
matplotlib = "^3.10.1"
stable-baselines3 = "^2.4.1"  # Pinning to a version compatible with torch 2.2.x
torch = "^2.2.2"  
scipy = "^1.15.2"
seaborn = "^0.13.2"
jupyter = "^1.1.1"
tushare = "^1.4.19"
backtrader = "^1.9.78.123"
empyrical = "^0.5.5"
alpaca-trade-api = "^3.2.0"
futu-api = "^9.1.5108"
pandas-market-calendars = "^4.6.1"
polygon-api-client = "^1.14.4"
alpaca-py = "^0.37"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
